FROM   docker.elastic.co/elasticsearch/elasticsearch:6.2.2

RUN  /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:6.2.2